/**
 * Clean aliases for the generated Prisma model row types.
 *
 * The Prisma 7 client exports row types with a `Model` suffix (`JobModel`).
 * Re-exporting them here keeps application code reading as `Job`, `Item`,
 * `Listing` and so on, and gives us one place to look when the generator
 * changes its naming again.
 */
export type {
  AIAnalysisModel as AIAnalysis,
  AIJobModel as AIJob,
  AIUsageModel as AIUsage,
  AccountModel as Account,
  AnalyticsEventModel as AnalyticsEvent,
  AppSettingModel as AppSetting,
  AuditLogModel as AuditLog,
  ComparableModel as Comparable,
  ContentBlockModel as ContentBlock,
  CreditLedgerModel as CreditLedger,
  DownloadArtifactModel as DownloadArtifact,
  EmailLogModel as EmailLog,
  EmailTemplateModel as EmailTemplate,
  EncryptedTokenModel as EncryptedToken,
  ExportJobModel as ExportJob,
  ExternalEventModel as ExternalEvent,
  ExternalListingModel as ExternalListing,
  FeatureFlagModel as FeatureFlag,
  ImpersonationModel as Impersonation,
  ItemModel as Item,
  ItemFactModel as ItemFact,
  ItemPhotoModel as ItemPhoto,
  ItemRevisionModel as ItemRevision,
  JobModel as Job,
  ListingModel as Listing,
  ListingRevisionModel as ListingRevision,
  ListingStatusEventModel as ListingStatusEvent,
  ListingVariantModel as ListingVariant,
  ModerationFlagModel as ModerationFlag,
  NotificationModel as Notification,
  NotificationPreferenceModel as NotificationPreference,
  OAuthStateModel as OAuthState,
  PlanModel as Plan,
  PlanEntitlementModel as PlanEntitlement,
  PlatformModel as Platform,
  PlatformCapabilityModel as PlatformCapability,
  PlatformConnectionModel as PlatformConnection,
  PlatformTemplateModel as PlatformTemplate,
  PriceSuggestionModel as PriceSuggestion,
  PromptTemplateModel as PromptTemplate,
  PromptVersionModel as PromptVersion,
  PublicationAttemptModel as PublicationAttempt,
  RateLimitModel as RateLimit,
  SaleRecordModel as SaleRecord,
  SessionModel as Session,
  StripeEventModel as StripeEvent,
  SubscriptionModel as Subscription,
  SupportNoteModel as SupportNote,
  SystemIncidentModel as SystemIncident,
  UserModel as User,
  UserPreferenceModel as UserPreference,
  VerificationModel as Verification,
  WebhookEventModel as WebhookEvent,
  WorkspaceModel as Workspace,
  WorkspaceMemberModel as WorkspaceMember,
} from '@/generated/prisma/models';
